algo = input('Digite algo: ')
print('Tipo primitivo:', type(algo))
print('Só tem espaços?', algo.isspace())
print('É um número?', algo.isnumeric())
print('É alfabético?', algo.isalpha())
print('É alfanumérico?', algo.isalnum())
print('Está maiúsculo?', algo.isupper())
print('Está minúsculo?', algo.islower())
print('Está capitalizado?', algo.istitle())